theme:
    name: material
    custom_dir: overrides
    language: en
#    features:
#        - instant # (still experimental) feature fails to load images when folder changes
    favicon: legacy/media/favicon.ico
    logo: v2.0/assets/icons/logo.svg
    logobw: v2.0/assets/icons/logo-bw.svg
    palette:
        -   scheme: default
            toggle:
                icon: assets/icons/dark-mode.svg
                name: Night mode
        -   scheme: slate
            toggle:
                icon: assets/icons/light-mode.svg
                name: Light mode
    font:
        text: Circular Std
        code: Ubuntu Mono
    icon:
        repo: fontawesome/brands/github
markdown_extensions:
    - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/ (in material theme)
    - codehilite
    - meta
    # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
    - pymdownx.superfences
    - pymdownx.magiclink
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

links:
    - title: Support
      url: google.com
    - title: Community
      url: google.com
    - title: FAQ
      url: google.com
    - title: Release Notes
      url: google.com
plugins:
    - search # necessary for search to work
 #   - autolinks
    - awesome-pages:
 #       strict: false
    - git-revision-date-localized
 #   - minify:
 #       minify_html: true
    - redirects:
        redirect_maps:
            'redir.md': 'index.md'
#    - monorepo

# Project information
site_name: Developer center
site_description: Documentation portal for enterprise-level Microsoft .NET ecommerce platform Virto Commerce.
site_author: Virto Commerce
site_url: https://virtocommerce.com/docs/latest

# Repository
repo_name: VirtoCommerce/vc-platform
repo_url: https://github.com/VirtoCommerce/vc-platform
edit_uri: edit/dev/docs/

# Copyright
copyright: Copyright &copy; 2022. All rights reserved.

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/VirtoCommerce
      - icon: fontawesome/brands/facebook
        link: https://facebook.com/VirtoCommerce
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/virtocommerce?lang=en
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/virto-commerce/
    search:
        icon: assets/icons/search.svg
    rss:
        icon: assets/icons/rss.svg
    main_page:
        top_cards:
            -   title: Architect
                icon: assets/icons/package.svg
                description: I need to build the platform's architecture or learn how I can do that.
            -   title: User
                icon: assets/icons/person.svg
                description: I use or am going to use Virto solutions on a regular basis.
            -   title: Developer
                icon: assets/icons/code-square.svg
                description: I need to know how the Virto platform works so that I may customize it best for my team or customers.
            -   title: Business Analyst
                icon: assets/icons/briefcase.svg
                description: I need to know how to implement Virto solutions across my team or externally.
        wide_cards:
            -   title: B2C solution
                icon: b2b-second.svg
                description: Learn how to build an online store your customers will buy goods and services from.
                link: docs/under-construction.md
            -   title: E-commerce platform
                icon: platform.svg
                description: Cloud techs are currently in the forefront of the IT industry. Learn how to them with Virto.
                link: docs/under-construction.md
            -   title: VirtoCloud
                icon: cloud.svg
                description: Cloud techs are currently in the forefront of the IT industry. Learn how to them with Virto.
                link: docs/under-construction.md
            -   title: Marketplace
                icon: marketplace.svg
                description: Virto Commerce allows you to build your very own unique online marketplace. See how!
                link: docs/under-construction.md
        education:
            - title: Videos
              description: Explore our video tutorials
              image: assets/icons/videos.png
            - title: Blog
              description: Hints, tips and so much more!
              image: assets/icons/articles.png
            - title: Videos
              description: Explore our video tutorials
              image: assets/icons/videos-second.png
            - title: Code samples
              description: Most used code samples
              image: assets/icons/stories.png
extra_javascript:
    - legacy/scripts/scripts-loader.js

extra_css:
    - v2.0/assets/stylesheets/main.css
    - v2.0/assets/stylesheets/fonts.css
