# v3.200.11
name: Release hotfix

on:
  workflow_dispatch:
    inputs:
      incrementVersion:
        description: 'Increment automatically patch version before release created.'
        required: true
        default: true
        type: boolean

jobs:
  test:
    needs:
      [increment-version]
    uses: VirtoCommerce/.github/.github/workflows/test-and-sonar.yml@v3.200.11
    secrets:
      sonarToken: ${{ secrets.SONAR_TOKEN }}

  build:
    needs:
      [increment-version]
    uses: VirtoCommerce/.github/.github/workflows/build.yml@v3.200.11
    with:
      uploadPackage: 'true'
      uploadDocker: 'true'
      imageName: 'platform'
      forceVersionSuffix: 'false'
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}

  get-metadata:
    needs:
      [increment-version]
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Changelog
      id: changelog
      uses: VirtoCommerce/vc-github-actions/changelog-generator@master

  publish-docker:
    needs:
      [build, get-metadata]
    uses: VirtoCommerce/.github/.github/workflows/publish-docker.yml@v3.200.11
    with:
      fullKey: ${{ needs.build.outputs.dockerFullKey }}
      shortKey: '${{ needs.build.outputs.dockerShortKey }}-'
      dockerTar: 'image.tar'
      publishToDocker: 'true'
    secrets:
      envPAT: ${{ secrets.GITHUB_TOKEN }}
      dockerUser: ${{ secrets.DOCKER_USERNAME }}
      dockerToken: ${{ secrets.DOCKER_TOKEN }}

  publish-github-release:
    needs:
      [build, get-metadata]
    uses: VirtoCommerce/.github/.github/workflows/publish-github.yml@v3.200.11
    with:
      fullKey: ${{ needs.build.outputs.packageFullKey }}
      changeLog: '${{ needs.get-metadata.outputs.changeLog }}'

    secrets:
      envPAT: ${{ secrets.GITHUB_TOKEN }}
      nugetKey: ${{ secrets.NUGET_KEY }}

  increment-version:
    if: ${{ github.event.inputs.incrementVersion }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      if: ${{ github.event.inputs.incrementVersion }}
      uses: actions/checkout@v3

    - name: Install VirtoCommerce.GlobalTool
      if: ${{ github.event.inputs.incrementVersion }}
      uses: VirtoCommerce/vc-github-actions/setup-vcbuild@master

    - name: Setup Git Credentials
      if: ${{ github.event.inputs.incrementVersion }}
      uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
      with:
        githubToken: ${{ secrets.REPO_TOKEN }}

    - name: Increment Version
      if: ${{ github.event.inputs.incrementVersion }}
      run: |
        vc-build IncrementPatch
        git add ${{ github.workspace }}/Directory.Build.props
        git commit -m "ci: Auto IncrementPatch"
        git push
